### ISSUE TITLE
tensorrt deb link is broken

### ISSUE THREAD

**Issue by wwdok** [hfnvbh/colab-trt-pose#1]
Hi, guy, thank you for sharing this repo that make me can have a quick experience of pose estimation !
In the colab notebook, i find the tensorrt deb can not be downloaded now, so i didn't install tensorrt. But finnally i can run successfully through the whole notebook, and it produce the output video. So i want to ask what is the influrence of missing tensorrt here ?
![image](https://user-images.githubusercontent.com/43233772/97077361-b1eaa000-1615-11eb-90c8-b6065b21c642.png)

**Comment by hfnvbh** [comment]
Hi @wwdok, glad that you find this repo useful.

It seems like full tensorrt package isn't needed now, installation of runtime binaries is enough. 
I think I needed it for some other experiments.
I will remove this sections.

Thank you for this information.
